# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20180119_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithospital',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
