# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 08:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20180119_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visithospital',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
